version: 2

project_name: "obot"

builds:
  - id: build
    main: .
    goos:
      - linux
      # - darwin
      # - windows
    goarch:
      - amd64
      # - arm64
    ldflags:
      - -X "github.com/jrmatherly/obot-entraid/pkg/version.Tag=v{{ .Version }}"

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

release:
  github:
    owner: "jrmatherly"
    name: "obot-entraid"
  make_latest: true
  prerelease: auto
