apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - credentials
    providers:
      - kms:
          apiVersion: v2
          name: aws-kms
          endpoint: unix:///tmp/aws-cred-socket.sock
          timeout: 3s
