apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - credentials
    providers:
      - kms:
          apiVersion: v2
          name: azure-kms
          endpoint: unix:///tmp/azure-cred-socket.sock
