{{- if and .Values.artifactPersistence.enabled (not .Values.artifactPersistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-artifacts-pvc
  labels:
    {{- include "obot.labels" . | nindent 4 }}
spec:
  {{- if .Values.artifactPersistence.storageClass }}
  storageClassName: {{ .Values.artifactPersistence.storageClass }}
  {{- end }}
  accessModes:
  {{- range .Values.artifactPersistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.artifactPersistence.size | quote }}
{{- end }}
