{{- if not .Values.config.existingSecret -}}
{{- if not .Values.dev.useEmbeddedDb }}
{{- $_ := required "For production use, you must provide a value for `config.OBOT_SERVER_DSN`. For testing or development purposes, you can set `dev.useEmbeddedDb` to true." .Values.config.OBOT_SERVER_DSN -}}
{{- end }}
{{- $secretName := ( include "obot.config.secretName" . ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "obot.labels" . | nindent 4 }}
  name: {{ include "obot.config.secretName" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if and (toString $value) (ne $key "existingSecret") }}
  {{ $key }}: {{ toString $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if gt (len .Values.mcpImagePullSecrets) 0 }}
  OBOT_SERVER_MCPIMAGE_PULL_SECRETS: {{ include "obot.config.mcpImagePullSecrets" . | quote }}
  {{- end }}
  {{- if eq .Values.config.OBOT_BOOTSTRAP_TOKEN "" }}
    {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
    {{- if $existing }}
      {{- $val := index $existing.data "OBOT_BOOTSTRAP_TOKEN" }}
  OBOT_BOOTSTRAP_TOKEN: {{ $val | quote }}
    {{- else }}
      {{- $random := randAlphaNum 32 }}
  OBOT_BOOTSTRAP_TOKEN: {{ $random | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
