{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "obot.labels" . | nindent 4 }}
  name: {{ include "obot.config.secretName" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if (toString $value) }}
  {{ $key }}: {{ toString $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}
