{{- if not .Values.config.existingSecret -}}
{{- if not .Values.dev.useEmbeddedDb }}
# {{- required "For production use, you must provide a value for `config.OBOT_SERVER_DSN`. For testing or development purposes, you can set `dev.useEmbeddedDb` to true." .Values.config.OBOT_SERVER_DSN | b64enc }}
{{- end }}
{{- $secretName := ( include "obot.config.secretName" . ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "obot.labels" . | nindent 4 }}
  name: {{ include "obot.config.secretName" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if (toString $value) }}
  {{ $key }}: {{ toString $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.config.OBOT_SERVER_MCPRUNTIME_BACKEND "kubernetes" }}
  OBOT_SERVER_MCPNAMESPACE: {{ include "obot.config.mcpNamespace" . | b64enc }}
  {{- if gt (len .Values.mcpImagePullSecrets) 0 }}
  OBOT_SERVER_MCPIMAGE_PULL_SECRETS: {{ include "obot.config.mcpImagePullSecrets" . | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.mcpServerDefaults.affinity }}
  OBOT_SERVER_MCPK8S_SETTINGS_AFFINITY: {{ .Values.mcpServerDefaults.affinity | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.mcpServerDefaults.tolerations }}
  OBOT_SERVER_MCPK8S_SETTINGS_TOLERATIONS: {{ .Values.mcpServerDefaults.tolerations | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.mcpServerDefaults.resources }}
  OBOT_SERVER_MCPK8S_SETTINGS_RESOURCES: {{ .Values.mcpServerDefaults.resources | toJson | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.config.OBOT_BOOTSTRAP_TOKEN "" }}
    {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
    {{- if $existing }}
      {{- $val := index $existing.data "OBOT_BOOTSTRAP_TOKEN" }}
  OBOT_BOOTSTRAP_TOKEN: {{ $val }}
    {{- else }}
      {{- $random := randAlphaNum 32 }}
  OBOT_BOOTSTRAP_TOKEN: {{ $random | b64enc }}
    {{- end }}
  {{- end }}
{{- end -}}
