{{- if eq .Values.config.existingSecret "" -}}
apiVersion: v1
data:
  {{- if .Values.config.awsAccessKeyID }}
  awsAccessKeyID: {{ .Values.config.awsAccessKeyID | b64enc }}
  {{- end }}
  {{- if .Values.config.awsRegion }}
  awsRegion: {{ .Values.config.awsRegion | b64enc }}
    {{- end }}
  {{- if .Values.config.awsSecretAccessKey }}
  awsSecretAccessKey: {{ .Values.config.awsSecretAccessKey | b64enc }}
    {{- end }}
  {{- if .Values.config.nahThreadiness }}
  nahThreadiness: {{ .Values.config.nahThreadiness | b64enc }}
    {{- end }}
  {{- if .Values.config.knowledgeFileWorkers }}
  knowledgeFileWorkers: {{ .Values.config.knowledgeFileWorkers | b64enc }}
    {{- end }}
  {{- if .Values.config.kinmDBConnections }}
  kinmDBConnections: {{ .Values.config.kinmDBConnections | b64enc }}
    {{- end }}
  {{- if .Values.config.ignoreInactiveObjects }}
  ignoreInactiveObjects: {{ .Values.config.ignoreInactiveObjects | b64enc }}
    {{- end }}
  {{- if .Values.config.gcpKMSKeyURI }}
  gcpKMSKeyURI: {{ .Values.config.gcpKMSKeyURI | b64enc }}
    {{- end }}
  {{- if .Values.config.githubAuthToken }}
  githubAuthToken: {{ .Values.config.githubAuthToken | b64enc }}
    {{- end }}
  {{- if .Values.config.obotServerAuthAdminEmails }}
  obotServerAuthAdminEmails: {{ .Values.config.obotServerAuthAdminEmails | b64enc }}
    {{- end }}
  {{- if .Values.config.obotServerDSN }}
  obotServerDSN: {{ .Values.config.obotServerDSN | b64enc }}
    {{- end }}
  {{- if .Values.config.obotBootstrapToken }}
  obotBootstrapToken: {{ .Values.config.obotBootstrapToken | b64enc }}
    {{- end }}
  {{- if .Values.config.obotServerHostname }}
  obotServerHostname: {{ .Values.config.obotServerHostname | b64enc }}
    {{- end }}
  {{- if .Values.config.obotWorkspaceProviderType }}
  obotWorkspaceProviderType: {{ .Values.config.obotWorkspaceProviderType | b64enc }}
    {{- end }}
  {{- if .Values.config.openaiApiKey }}
  openaiApiKey: {{ .Values.config.openaiApiKey | b64enc }}
    {{- end }}
  {{- if .Values.config.workspaceProviderS3BaseEndpoint }}
  workspaceProviderS3BaseEndpoint: {{ .Values.config.workspaceProviderS3BaseEndpoint | b64enc }}
    {{- end }}
  {{- if .Values.config.workspaceProviderS3Bucket }}
  workspaceProviderS3Bucket: {{ .Values.config.workspaceProviderS3Bucket | b64enc }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "obot.labels" . | nindent 4 }}
  name: {{ include "obot.config.secretName" . }}
type: Opaque
{{- end -}}