{{- if or .Values.serviceAccount.create (ne .Values.config.OBOT_SERVER_MCPBASE_IMAGE "") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obot.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}