{{- if or .Values.serviceAccount.create (eq .Values.config.OBOT_SERVER_MCPRUNTIME_BACKEND "kubernetes") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obot.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "obot.labels" . | nindent 4 }}
{{- end }}
