name: Build release tools

permissions:
  id-token: write
  contents: read
  packages: write

on:
  repository_dispatch:
    types:
      - tools

jobs:
  enterprise-build:
    if: github.event.repository.full_name == 'obot-platform/enterprise-tools' || github.event.repository.full_name == 'obot-platform/tools'
    runs-on: depot-ubuntu-22.04
    concurrency:
      group: enterprise-build
      cancel-in-progress: true
    steps:
      - name: Print the dispatch source
        run: echo "Dispatched by ${{ github.event.repository.full_name }}"

      - uses: actions/checkout@v4
        with:
          repository: 'obot-platform/obot'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push enterprise-tools Docker image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          push: true
          pull: true
          file: Dockerfile-tools
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/enterprise-tools:latest
          secrets: |
            GITHUB_TOKEN=${{ secrets.GHCR_TOKEN }}
          build-args: |
            TOOL_REGISTRY_REPOS=github.com/obot-platform/tools,github.com/obot-platform/enterprise-tools

  oss-build:
    if: github.event.repository.full_name == 'obot-platform/tools'
    runs-on: depot-ubuntu-22.04
    concurrency:
      group: oss-build
      cancel-in-progress: true
    steps:
      - name: Print the dispatch source
        run: echo "Dispatched by ${{ github.event.repository.full_name }}"

      - uses: actions/checkout@v4
        with:
          repository: 'obot-platform/obot'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push oss-tools Docker image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          push: true
          pull: true
          file: Dockerfile-tools
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/oss-tools:latest
          secrets: |
            GITHUB_TOKEN=${{ secrets.GHCR_TOKEN }}
          build-args: |
            TOOL_REGISTRY_REPOS=github.com/obot-platform/tools