name: Test Docker Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - chart/**

env:
  PROVIDERS_IMAGE: ghcr.io/accelerate-data/providers-vibedata:latest
  ENCRYPTION_BINS_IMAGE: ghcr.io/accelerate-data/providers-vibedata/encryption-bins:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            PROVIDERS_IMAGE=${{ env.PROVIDERS_IMAGE }}
            ENCRYPTION_BINS_IMAGE=${{ env.ENCRYPTION_BINS_IMAGE }}
