name: Test Docker Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - chart/**

env:
  BASE_IMAGE: ghcr.io/accelerate-data/obot/base:latest
  PROVIDERS_IMAGE: ghcr.io/accelerate-data/providers-vibedata:latest
  ENCRYPTION_BINS_IMAGE: ghcr.io/accelerate-data/providers-vibedata/encryption-bins:latest

jobs:
  build:
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Depot
        uses: depot/setup-action@v1

      - name: Build Docker Image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            PROVIDERS_IMAGE=${{ env.PROVIDERS_IMAGE }}
            ENCRYPTION_BINS_IMAGE=${{ env.ENCRYPTION_BINS_IMAGE }}
